import { v4 as uuid } from "uuid";

export const foodList = [
  {
    id: uuid(),
    name: "boiled beans",
    type: "food",
    amount: "200",
    url: "https://www.w3schools.com/w3images/nature.jpg",
    description: "",
  },

  {
    id: uuid(),
    name: "porridge beans",
    type: "food",
    amount: "250",
    url: "appImages/foods/porridgebeans.png",
    description: "",
  },
  {
    id: uuid(),
    name: "white rice with stew",
    type: "food",
    amount: "500",
    url: "appImages/foods/whiterice_stew.png",
    description: "",
  },
  {
    id: uuid(),
    name: "fried rice",
    type: "food",
    amount: "500",
    url: "appImages/foods/friedrice.png",
    description: "",
  },

  {
    id: uuid(),
    name: "jollof rice",
    type: "food",
    amount: "500",
    url: "appImages/foods/jollof_rice.png",
    description: "",
  },

  {
    id: uuid(),
    name: "spaghetti with stew",
    type: "food",
    amount: "500",
    url: "appImages/foods/spaghetti_with_stew.png",
    description: "",
  },

  {
    id: uuid(),
    name: "fried spaghetti",
    type: "food",
    amount: "500",
    url: "appImages/foods/friedspaghetti.png",
    description: "",
  },

  {
    id: uuid(),
    name: "jollof spaghetti",
    type: "food",
    amount: "500",
    url: "appImages/foods/jollof_spag.png",
    description: "",
  },

  {
    id: uuid(),
    name: "coconut rice",
    type: "food",
    amount: "500",
    url: "appImages/foods/coconutrice.png",
    description: "",
  },
  {
    id: uuid(),
    name: "salad",
    type: "food",
    amount: "500",
    url: "appImages/foods/salad.png",
    description: "",
  },
  {
    id: uuid(),
    name: "amala",
    type: "food",
    amount: "100",
    url: "appImages/foods/amala.png",
    description: "",
  },
  {
    id: uuid(),
    name: "eba",
    type: "food",
    amount: "100",
    url: "appImages/foods/eba.png",
    description: "",
  },
  {
    id: uuid(),
    name: "fufu",
    type: "food",
    amount: "100",
    url: "appImages/foods/fufu.png",
    description: "",
  },
  {
    id: uuid(),
    name: "wheat",
    type: "food",
    amount: "150",
    url: "appImages/foods/wheat.png",
    description: "",
  },
  {
    id: uuid(),
    name: "starch",
    type: "food",
    amount: "100",
    url: "appImages/foods/starch.png",
    description: "",
  },
  {
    id: uuid(),
    name: "afang soup",
    type: "food",
    amount: "1000",
    url: "appImages/foods/afang.png",
    description: "",
  },
  {
    id: uuid(),
    name: "assorted meat peppersoup",
    type: "food",
    amount: "1000",
    url: "appImages/foods/assorted_meat_peppersoup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "bitter leaf",
    type: "food",
    amount: "1000",
    url: "appImages/foods/bitter_leaf.png",
    description: "",
  },
  {
    id: uuid(),
    name: "cowtail peppersoup",
    type: "food",
    amount: "1500",
    url: "appImages/foods/cowtail_peppersoup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "egwusi soup",
    type: "food",
    amount: "1000",
    url: "appImages/foods/egwusi_soup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "ewedu soup",
    type: "food",
    amount: "500",
    url: "appImages/foods/ewedu_soup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "gbegiri soup",
    type: "food",
    amount: "500",
    url: "appImages/foods/gbegiri_soup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "goat meat soup",
    type: "food",
    amount: "1500",
    url: "appImages/foods/goatmeat_peppersoup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "oha soup",
    type: "food",
    amount: "1000",
    url: "appImages/foods/oha_soup.png",
    description: "",
  },
  {
    id: uuid(),
    name: "white soup",
    type: "food",
    amount: "1500",
    url: "appImages/foods/white_soup.png",
    description: "",
  },
];
